In [19]:
#Supervised ML
#Regression : Multivariate / Multiple Linear regression


In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat
import sklearn.linear_model
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
import warnings as wr
import pickle

In [21]:
data = pd.read_csv("https://raw.githubusercontent.com/yash240990/Python/master/Startups_Data.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [23]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [24]:
#independend variable
x = ['R&D Spend', 'Administration', 'Marketing Spend', 'State']
x = data[x].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [25]:
#depended variable
y = data.Profit.values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [26]:
#labelEncoder
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.compose import ColumnTransformer

label_encoder = LabelEncoder()
x[:,3] = label_encoder.fit_transform(x[:,3])
transformer = ColumnTransformer(transformers=[("onehot",OneHotEncoder(),[3])],remainder='passthrough')
x = transformer.fit_transform(x)
x = x.astype(int)




In [27]:
x

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     0,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     0,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     0,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     0,      0,      1,

In [28]:
#Split the dataset into Training amd Testing Subset
from sklearn.model_selection import train_test_split
#test_size=0.2 means 20% of data is send for testing and rest 80% for training
x_train , x_test ,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)


In [29]:
print('Original Shape')
print(x.shape)
print(y.shape)
print('After splitting')
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

Original Shape
(50, 6)
(50,)
After splitting
(40, 6)
(40,)
(10, 6)
(10,)


In [30]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [31]:
# pickle the model
pickle.dump(mlr,open('MLR_Model.pkl','wb'))

In [32]:
pred_values = mlr.predict(x_test)
pred_values

array([103015.24646785, 132581.94062687, 132448.09397396,  71975.74395634,
       178537.52007853, 116161.05196901,  67851.47761321,  98791.74112204,
       113969.41004647, 167921.22416079])

In [33]:
from sklearn.metrics import r2_score
acc = r2_score(y_test,pred_values)
print('Accuracy of model:',acc*100)

Accuracy of model: 93.47065984136125


In [34]:
#Final Prediction

#Take Input from user
california = int(input('Is startup is in California ? Enter 1 if yes else 0:'))
florida = int(input('Is startup is in Florida ? Enter 1 if yes else 0: '))
newyork = int(input('Is startup is in NewYork ? Enter 1 if yes else 0:'))
r_d = int(input('Enter Research & Development Spend: '))
admin = int(input('Enter Administration Spend: '))
market = int(input('Enter Marketing Spend: '))

#Store input in Dictonary
user_input = {'california':california, 'florida': florida, 'newyork': newyork, 'r_d':r_d,'admin': admin, 'market': market}


#Convert Dictonary into DataFrames
user_data = pd.DataFrame (user_input, index=[0])
user_data

Is startup is in California ? Enter 1 if yes else 0:0
Is startup is in Florida ? Enter 1 if yes else 0: 1
Is startup is in NewYork ? Enter 1 if yes else 0:0
Enter Research & Development Spend: 1
Enter Administration Spend: 12345
Enter Marketing Spend: 54523


california  florida  newyork  r_d  admin  market
0           0        1        0    1  12345   54523

In [35]:
wr.filterwarnings('ignore')   #for hidding warnings use this line for any code
predicted_proff = mlr.predict(user_data)
int(predicted_proff[0])

43998